# Generated by Django 2.2.7 on 2020-03-01 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200301_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='drat',
            new_name='draft',
        ),
    ]
