# Generated by Django 2.2.7 on 2020-03-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_read_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.IntegerField(default=0),
        ),
    ]
